name: on_user_created
description: Receive CloudEvents on user creation and save data to Firestore.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.0.0
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0
  json_annotation: ^4.0.1

dev_dependencies:
  json_serializable: ^4.1.1
  build_runner: ^2.0.2
  functions_framework_builder: ^0.4.1
  http: ^0.13.3
  test: ^1.17.3
  test_process: ^2.0.0
